apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: adrien1975@live.fr
    privateKeySecretRef:
      name: argocd-secret
    solvers:
      - http01:
          ingress:
            class: nginx
