---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud

resources:
  - namespace.yml

  - volume.yml
  - volume-claim.yml
  - configmap.yml
  - deployment.yml
  - service.yml
  - ingress.yml
