---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-apps
spec:
  capacity:
    storage: 1Gi # TODO: More!
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  claimRef:
    namespace: nextcloud
    name: nextcloud-apps
  local:
    path: /data/nextcloud-apps
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - arkilin # TODO X D
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-config
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  claimRef:
    namespace: nextcloud
    name: nextcloud-config
  local:
    path: /data/nextcloud-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - arkilin # TODO X D
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
spec:
  capacity:
    storage: 5Gi # TODO: More!
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  claimRef:
    namespace: nextcloud
    name: nextcloud-data
  local:
    path: /data/nextcloud-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - arkilin # TODO X D
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-theme
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  claimRef:
    namespace: nextcloud
    name: nextcloud-theme
  local:
    path: /data/nextcloud-theme
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - arkilin # TODO X D
