---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeName: nextcloud-apps
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeName: nextcloud-config
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeName: nextcloud-data
  resources:
    requests:
      storage: 738Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-theme
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeName: nextcloud-theme
  resources:
    requests:
      storage: 1Gi
