---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeName: sonarr-config
  resources:
    requests:
      storage: 1Gi
