---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bitwarden
  labels:
    app: bitwarden
data:
  SMTP_HOST: "mail.litarvan.com"
  SMTP_FROM: "noreply@passwords.litarvan.com"
  SMTP_PORT: "587"
  SMTP_SECURITY: "starttls"
  WEBSOCKET_ENABLED: "true"
  DATA_FOLDER: "/data"
  DOMAIN: "https://passwords.litarvan.com"
  ROCKET_WORKERS: "4"
  SHOW_PASSWORD_HINT: "false"
  WEB_VAULT_ENABLED: "true"
  ROCKET_PORT: "8080"
  SIGNUPS_ALLOWED: "false"
  INVITATIONS_ALLOWED: "true"
  # YUBICO_CLIENT_ID: "123123"
  # YUBICO_SECRET_KEY: "Vsdfsew434fsdfsdfsdf="