---
apiVersion: v1
kind: Service
metadata:
  name: bitwarden
spec:
  type: ClusterIP
  selector:
    app: bitwarden
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: websocket
      port: 3012
      targetPort: 3012
      protocol: TCP
