---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitwarden
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  claimRef:
    namespace: bitwarden
    name: bitwarden
  local:
    path: /data/bitwarden
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - arkilin # TODO X D