---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeName: bitwarden
  resources:
    requests:
      storage: 100Gi