---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flood
  labels:
    app: flood
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: flood
  template:
    metadata:
      labels:
        app: flood
    spec:
      containers:
        - name: flood
          image: jesec/flood:master-distroless
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - name: http
              containerPort: 3001
          volumeMounts:
            - name: flood-config
              mountPath: /config
            - name: flood-data
              mountPath: /data
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              memory: 512Mi
      volumes:
        - name: flood-config
          persistentVolumeClaim:
            claimName: flood-config
        - name: flood-data
          persistentVolumeClaim:
            claimName: flood-data
    # securityContext:
    #   runAsUser: 1000
    #   runAsGroup: 1000
    #   fsGroup: 1000
    #   runAsNonRoot: true