---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flood-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeName: flood-config
  resources:
    requests:
      storage: 250Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flood-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeName: flood-data
  resources:
    requests:
      storage: 750Mi
