---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haste-server
spec:
  rules:
    - host: code.litarvan.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: haste-server
                port:
                  name: http
  tls:
    - hosts:
        - code.litarvan.com
      secretName: code-tls
