---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: haste-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeName: haste-server
  resources:
    requests:
      storage: 50Gi