---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: meow

resources:
  - namespace.yml

  - volume.yml
  - volume-claim.yml

  - qbittorrent/
  - jackett/
  - flood/
  - radarr/
  - sonarr/
  - jellyfin/

