---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: torrents
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  claimRef:
    namespace: meow
    name: torrents
  local:
    path: /data/nvme1/meow-torrents
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - leviathan-alpha