---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrents
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local
  volumeName: torrents
  resources:
    requests:
      storage: 2Ti