apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crosslink
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://github.com/Litarvan/leviathan.git
    targetRevision: HEAD
    path: k8s/apps/crosslink
  destination:
    name: in-cluster
    namespace: crosslink