---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - cert-manager.yml
  - argocd.yml

  - bitwarden.yml
  - crosslink.yml
  - epilink.yml
  - haste-server.yml
  - meow.yml
