---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: epilink

resources:
  - namespace.yml

  - redis/deployment.yml
  - redis/service.yml
  - volume.yml

  - volume-claim.yml
  - deployment.yml
  - service.yml
  - ingress.yml
