---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: epilink
spec:
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  claimRef:
    namespace: epilink
    name: epilink
  local:
    path: /data/epilink
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - arkilin # TODO X D