---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeName: minecraft
  resources:
    requests:
      storage: 50Gi
