---
apiVersion: v1
kind: Service
metadata:
  name: redis
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: 6379
      protocol: TCP
      name: redis
      targetPort: 6379
