---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeName: radarr-config
  resources:
    requests:
      storage: 100Mi
