---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeName: qbittorrent-config
  resources:
    requests:
      storage: 100Mi
