---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crosslink
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeName: crosslink
  resources:
    requests:
      storage: 1Gi