---
apiVersion: v1
kind: Service
metadata:
  name: remote-clion
spec:
  type: NodePort
  selector:
    app: remote-clion
  ports:
    - name: ssh
      port: 22
      nodePort: 30101
    - name: remote
      port: 5990
      nodePort: 30102
