---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: remote-clion-ssh
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeName: remote-clion-ssh
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: remote-clion-flake
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeName: remote-clion-flake
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: remote-clion-project
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeName: remote-clion-project
  resources:
    requests:
      storage: 500Mi