---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jackett-config
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  claimRef:
    namespace: meow
    name: jackett-config
  local:
    path: /data/meow-jackett-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - leviathan-alpha
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jackett-blackhole
spec:
  capacity:
    storage: 1Gi # TODO: More?
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  claimRef:
    namespace: meow
    name: jackett-blackhole
  local:
    path: /data/meow-jackett-blackhole
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - leviathan-alpha
